import type { PlanetConfig } from '../types/planet.types'

export const PLANETS: PlanetConfig[] = [
    {
        id: 'earth',
        name: 'Earth',
        modelPath: '/models/earth.glb',
        position: [0, 0, 0],
        displaySize: 10,
        rotationSpeed: 0.002,
        description: 'The only known harbor of life. A thin film of atmosphere wraps a world of deep oceans and ancient stone.',
        facts: [
            { label: 'Diameter', value: '12,742', unit: 'km' },
            { label: 'Distance to Sun', value: '149.6', unit: 'mil km' },
            { label: 'Day Length', value: '24', unit: 'hours' },
            { label: 'Moons', value: '1' },
            { label: 'Surface Temp', value: '15', unit: '°C avg' },
            { label: 'Gravity', value: '9.8', unit: 'm/s²' },
        ],
    },
    {
        id: 'mars',
        name: 'Mars',
        modelPath: '/models/mars.glb',
        position: [20, -8, -120],
        displaySize: 10,
        rotationSpeed: 0.0015,
        description: 'The red desert. Iron oxide dust coats a cold, cratered world that once held rivers and perhaps life.',
        facts: [
            { label: 'Diameter', value: '6,779', unit: 'km' },
            { label: 'Distance to Sun', value: '227.9', unit: 'mil km' },
            { label: 'Day Length', value: '24.6', unit: 'hours' },
            { label: 'Moons', value: '2' },
            { label: 'Surface Temp', value: '-60', unit: '°C avg' },
            { label: 'Gravity', value: '3.7', unit: 'm/s²' },
        ],
    },
    {
        id: 'jupiter',
        name: 'Jupiter',
        modelPath: '/models/jupiter.glb',
        position: [-25, 12, -260],
        displaySize: 10,
        rotationSpeed: 0.003,
        description: 'King of planets. A vast storm larger than Earth has raged for over three hundred years beneath its cloud bands.',
        facts: [
            { label: 'Diameter', value: '139,820', unit: 'km' },
            { label: 'Distance to Sun', value: '778.5', unit: 'mil km' },
            { label: 'Day Length', value: '9.9', unit: 'hours' },
            { label: 'Moons', value: '95' },
            { label: 'Surface Temp', value: '-110', unit: '°C avg' },
            { label: 'Gravity', value: '24.8', unit: 'm/s²' },
        ],
    },
    {
        id: 'saturn',
        name: 'Saturn',
        modelPath: '/models/saturn.glb',
        position: [30, -6, -400],
        displaySize: 30,
        rotationSpeed: 0.0018,
        description: 'Lord of the rings. Its iconic bands of ice and rock stretch vast distances yet are remarkably thin.',
        facts: [
            { label: 'Diameter', value: '116,460', unit: 'km' },
            { label: 'Distance to Sun', value: '1,432', unit: 'mil km' },
            { label: 'Day Length', value: '10.7', unit: 'hours' },
            { label: 'Moons', value: '146' },
            { label: 'Surface Temp', value: '-140', unit: '°C avg' },
            { label: 'Gravity', value: '10.4', unit: 'm/s²' },
        ],
    },
    {
        id: 'uranus',
        name: 'Uranus',
        modelPath: '/models/uranus.glb',
        position: [-20, 10, -540],
        displaySize: 25,
        rotationSpeed: 0.0015,
        description: 'The tilted giant. Uranus orbits the sun essentially on its side, its poles facing the sun in turn.',
        facts: [
            { label: 'Diameter', value: '50,724', unit: 'km' },
            { label: 'Distance to Sun', value: '2,867', unit: 'mil km' },
            { label: 'Day Length', value: '17.2', unit: 'hours' },
            { label: 'Moons', value: '28' },
            { label: 'Surface Temp', value: '-195', unit: '°C avg' },
            { label: 'Gravity', value: '8.7', unit: 'm/s²' },
        ],
    },
    {
        id: 'neptune',
        name: 'Neptune',
        modelPath: '/models/neptune.glb',
        position: [25, -10, -680],
        displaySize: 25,
        rotationSpeed: 0.0012,
        description: 'The windswept frontier. Neptune hosts the fastest winds in the solar system, reaching 2,100 km/h.',
        facts: [
            { label: 'Diameter', value: '49,244', unit: 'km' },
            { label: 'Distance to Sun', value: '4,495', unit: 'mil km' },
            { label: 'Day Length', value: '16.1', unit: 'hours' },
            { label: 'Moons', value: '16' },
            { label: 'Surface Temp', value: '-200', unit: '°C avg' },
            { label: 'Gravity', value: '11.2', unit: 'm/s²' },
        ],
    },
]